# Generated by Django 4.2.5 on 2023-09-12 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
                ('dt_create', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tb_backup',
            },
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('host_db', models.CharField(max_length=255)),
                ('port_db', models.IntegerField()),
                ('backup_path', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tb_environment',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('backup_path', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tb_project',
            },
        ),
        migrations.CreateModel(
            name='Restore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dt_restore', models.DateTimeField(auto_now_add=True)),
                ('destination_environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backup_manager.environment')),
                ('origin_backup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backup_manager.backup')),
            ],
            options={
                'db_table': 'tb_restore',
            },
        ),
        migrations.AddField(
            model_name='backup',
            name='environment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backup_manager.environment'),
        ),
        migrations.AddField(
            model_name='backup',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backup_manager.project'),
        ),
    ]
