# Generated by Django 4.2.5 on 2023-09-29 18:04

from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0018_improve_crontab_helptext'),
        ('backup_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='database',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backup_manager.database', verbose_name='Database'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Return Description'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='dt_create',
            field=models.DateTimeField(blank=True, help_text='Leave it _blank_ if the backup is to be done now  | Set it to a future date if the backup is to be scheduled  | Set it to a past date if the backup is already done', verbose_name='Reference Date'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='dt_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='dt_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='name',
            field=models.CharField(blank=True, help_text='Default: "{project.name}_{environment.name}_{date_time}"', max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='path',
            field=models.CharField(max_length=255, verbose_name='Path'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='status',
            field=models.CharField(choices=[('PD', 'PENDING'), ('ST', 'STARTED'), ('SC', 'SUCCESS'), ('FL', 'FAILED'), ('MN', 'MANUAL'), ('SD', 'SCHEDULED')], default='PD', max_length=2, verbose_name='Execution Status'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Celery Task ID'),
        ),
        migrations.AlterField(
            model_name='database',
            name='environment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backup_manager.environment', verbose_name='Environment'),
        ),
        migrations.AlterField(
            model_name='database',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backup_manager.host', verbose_name='Host'),
        ),
        migrations.AlterField(
            model_name='database',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='database',
            name='password',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, help_text='Overwrite the password of user used in periodic tasks (encrypted)', max_length=255, null=True, verbose_name='Password')),
        ),
        migrations.AlterField(
            model_name='database',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backup_manager.project', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='database',
            name='user',
            field=models.CharField(blank=True, help_text='Overwrite the user used in periodic tasks', max_length=255, null=True, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='environment',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='host',
            name='ip',
            field=models.CharField(max_length=255, verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='host',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='host',
            name='password',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, help_text='Password of user used in periodic tasks (encrypted)', max_length=255, null=True, verbose_name='Password')),
        ),
        migrations.AlterField(
            model_name='host',
            name='port',
            field=models.IntegerField(verbose_name='Port'),
        ),
        migrations.AlterField(
            model_name='host',
            name='user',
            field=models.CharField(blank=True, help_text='User used in periodic tasks', max_length=255, null=True, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='periodicdatabasebackup',
            name='database',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backup_manager.database', verbose_name='Database'),
        ),
        migrations.AlterField(
            model_name='periodicdatabasebackup',
            name='name',
            field=models.CharField(blank=True, help_text='Default: "Backup {database.project.name} - {database.environment.name} ({database.name}) [{self.periodic_task.crontab.human_readable}]"', max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='periodicdatabasebackup',
            name='periodic_task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.periodictask', verbose_name='Celery Periodic Task'),
        ),
        migrations.AlterField(
            model_name='periodicenvironmentbackup',
            name='environment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backup_manager.environment', verbose_name='Environment'),
        ),
        migrations.AlterField(
            model_name='periodicenvironmentbackup',
            name='name',
            field=models.CharField(blank=True, help_text='Default: "Backup {environment.name} [{self.periodic_task.crontab.human_readable}]"', max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='periodicenvironmentbackup',
            name='periodic_task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.periodictask', verbose_name='Celery Periodic Task'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='restore',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Return Description'),
        ),
        migrations.AlterField(
            model_name='restore',
            name='destination_database',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backup_manager.database', verbose_name='Destination Database'),
        ),
        migrations.AlterField(
            model_name='restore',
            name='dt_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Reference Date'),
        ),
        migrations.AlterField(
            model_name='restore',
            name='dt_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='restore',
            name='dt_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='restore',
            name='name',
            field=models.CharField(blank=True, help_text='Default: "{origin_backup} -> {destination_database}"', max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='restore',
            name='origin_backup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backup_manager.backup', verbose_name='Origin Backup'),
        ),
        migrations.AlterField(
            model_name='restore',
            name='status',
            field=models.CharField(choices=[('PD', 'PENDING'), ('ST', 'STARTED'), ('SC', 'SUCCESS'), ('FL', 'FAILED'), ('MN', 'MANUAL'), ('SD', 'SCHEDULED')], default='PD', max_length=2, verbose_name='Execution Status'),
        ),
        migrations.AlterField(
            model_name='restore',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Celery Task ID'),
        ),
    ]
