# Generated by Django 4.2.5 on 2023-09-13 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backup',
            name='dt_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='backup',
            name='dt_start',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='backup',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restore',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
