# Generated by Django 4.2.5 on 2023-09-29 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backup_manager', '0002_alter_backup_database_alter_backup_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backup',
            old_name='dt_create',
            new_name='dt_reference',
        ),
        migrations.RenameField(
            model_name='restore',
            old_name='dt_create',
            new_name='dt_reference',
        ),
    ]
