# Generated by Django 4.2.5 on 2023-09-13 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backup_manager', '0002_backup_dt_end_backup_dt_start_backup_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backup_manager.environment')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backup_manager.project')),
            ],
            options={
                'db_table': 'tb_database',
            },
        ),
    ]
