# Generated by Django 4.2.5 on 2023-09-25 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup_manager', '0003_alter_periodicbackup_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodicbackup',
            name='name',
            field=models.CharField(blank=True, help_text='Default: "Backup {database.project.name} - {database.environment.name} ({database.name})"', max_length=255),
        ),
    ]
