# Generated by Django 4.2.5 on 2023-10-05 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup_manager', '0003_rename_dt_create_backup_dt_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='status',
            field=models.CharField(choices=[('PD', 'PENDING'), ('ST', 'STARTED'), ('SC', 'SUCCESS'), ('FL', 'FAILED'), ('MN', 'MANUAL'), ('SD', 'SCHEDULED'), ('RV', 'REVOKING')], default='PD', max_length=2, verbose_name='Execution Status'),
        ),
        migrations.AlterField(
            model_name='restore',
            name='status',
            field=models.CharField(choices=[('PD', 'PENDING'), ('ST', 'STARTED'), ('SC', 'SUCCESS'), ('FL', 'FAILED'), ('MN', 'MANUAL'), ('SD', 'SCHEDULED'), ('RV', 'REVOKING')], default='PD', max_length=2, verbose_name='Execution Status'),
        ),
    ]
