# Generated by Django 4.2.5 on 2023-09-25 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backup_manager', '0004_alter_periodicbackup_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='periodicbackup',
            table='tb_periodic_database_backup',
        ),
    ]
