# Generated by Django 4.2.5 on 2023-09-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup_manager', '0005_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restore',
            old_name='dt_restore',
            new_name='dt_create',
        ),
        migrations.AddField(
            model_name='restore',
            name='dt_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restore',
            name='dt_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backup',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
