# Generated by Django 4.2.5 on 2023-09-15 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backup_manager', '0006_rename_dt_restore_restore_dt_create_restore_dt_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backup',
            name='environment',
        ),
        migrations.RemoveField(
            model_name='backup',
            name='project',
        ),
        migrations.AddField(
            model_name='backup',
            name='database',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backup_manager.database'),
            preserve_default=False,
        ),
    ]
