# Generated by Django 4.2.5 on 2023-09-25 10:42

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backup_manager', '0006_rename_periodicbackup_periodicdatabasebackup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='password',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, help_text='Overwrite the password of user used in periodic tasks (encrypted)', max_length=255, null=True)),
        ),
        migrations.AlterField(
            model_name='host',
            name='password',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, help_text='Password of user used in periodic tasks (encrypted)', max_length=255, null=True)),
        ),
    ]
