# Generated by Django 4.2.5 on 2023-09-15 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backup_manager', '0007_remove_backup_environment_remove_backup_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='environment',
            name='backup_path',
        ),
    ]
