# Generated by Django 4.2.5 on 2023-09-25 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0018_improve_crontab_helptext'),
        ('backup_manager', '0007_alter_database_password_alter_host_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodicEnvironmentBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Default: "Backup {environment.name}"', max_length=255)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backup_manager.environment')),
                ('periodic_task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.periodictask')),
            ],
            options={
                'db_table': 'tb_periodic_environment_backup',
            },
        ),
    ]
