# Generated by Django 4.2.5 on 2023-09-15 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backup_manager', '0009_alter_backup_dt_create_alter_backup_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restore',
            name='destination_environment',
        ),
        migrations.AddField(
            model_name='restore',
            name='destination_database',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backup_manager.database'),
            preserve_default=False,
        ),
    ]
