# Generated by Django 4.2.5 on 2023-09-15 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backup_manager', '0010_remove_restore_destination_environment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='backup_path',
        ),
    ]
