# Generated by Django 4.2.2 on 2023-09-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup_manager', '0011_remove_project_backup_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='backup',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restore',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backup',
            name='status',
            field=models.CharField(choices=[('NS', 'Not Started'), ('ST', 'Started'), ('SC', 'Success'), ('FL', 'Failed')], default='NS', max_length=2),
        ),
        migrations.AlterField(
            model_name='restore',
            name='status',
            field=models.CharField(choices=[('NS', 'Not Started'), ('ST', 'Started'), ('SC', 'Success'), ('FL', 'Failed')], default='NS', max_length=2),
        ),
    ]
