# Generated by Django 4.2.5 on 2023-09-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup_manager', '0012_backup_description_restore_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='status',
            field=models.CharField(choices=[('PD', 'PENDING'), ('ST', 'STARTED'), ('SC', 'SUCCESS'), ('FL', 'FAILED'), ('MN', 'MANUAL')], default='PD', max_length=2),
        ),
        migrations.AlterField(
            model_name='restore',
            name='status',
            field=models.CharField(choices=[('PD', 'PENDING'), ('ST', 'STARTED'), ('SC', 'SUCCESS'), ('FL', 'FAILED'), ('MN', 'MANUAL')], default='PD', max_length=2),
        ),
    ]
