# Generated by Django 4.2.5 on 2023-09-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup_manager', '0013_alter_backup_status_alter_restore_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='backup',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='restore',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='backup',
            name='dt_create',
            field=models.DateTimeField(blank=True, help_text='Leave it _blank_ if the backup is to be done now  | Set it to a future date if the backup is to be scheduled  | Set it to a past date if the backup is already done'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='status',
            field=models.CharField(choices=[('PD', 'PENDING'), ('ST', 'STARTED'), ('SC', 'SUCCESS'), ('FL', 'FAILED'), ('MN', 'MANUAL'), ('SD', 'SCHEDULED')], default='PD', max_length=2),
        ),
        migrations.AlterField(
            model_name='restore',
            name='name',
            field=models.CharField(blank=True, help_text='Default: "{origin_backup} -> {destination_database}"', max_length=255),
        ),
        migrations.AlterField(
            model_name='restore',
            name='status',
            field=models.CharField(choices=[('PD', 'PENDING'), ('ST', 'STARTED'), ('SC', 'SUCCESS'), ('FL', 'FAILED'), ('MN', 'MANUAL'), ('SD', 'SCHEDULED')], default='PD', max_length=2),
        ),
    ]
