# Generated by Django 4.2.5 on 2023-09-22 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0018_improve_crontab_helptext'),
        ('backup_manager', '0014_backup_task_id_restore_task_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodicTaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('interval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.intervalschedule')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.periodictask')),
            ],
        ),
    ]
