# Generated by Django 4.2.5 on 2023-09-22 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backup_manager', '0015_periodictaskmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PeriodicTaskModel',
        ),
    ]
