# Generated by Django 4.2.5 on 2023-09-22 12:45

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backup_manager', '0016_delete_periodictaskmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='password',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, help_text='Overwrite the password of user used in periodic tasks', max_length=255, null=True)),
        ),
        migrations.AddField(
            model_name='database',
            name='user',
            field=models.CharField(blank=True, help_text='Overwrite the user used in periodic tasks', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='password',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, help_text='Password of user used in periodic tasks', max_length=255, null=True)),
        ),
        migrations.AddField(
            model_name='host',
            name='user',
            field=models.CharField(blank=True, help_text='User used in periodic tasks', max_length=255, null=True),
        ),
    ]
