# Generated by Django 4.2.5 on 2023-09-22 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0018_improve_crontab_helptext'),
        ('backup_manager', '0017_database_password_database_user_host_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodicBackup',
            fields=[
                ('periodictask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_celery_beat.periodictask')),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backup_manager.database')),
            ],
            bases=('django_celery_beat.periodictask',),
        ),
    ]
