# Generated by Django 4.2.5 on 2023-09-22 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0018_improve_crontab_helptext'),
        ('backup_manager', '0018_periodicbackup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='periodicbackup',
            name='periodictask_ptr',
        ),
        migrations.AddField(
            model_name='periodicbackup',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='periodicbackup',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='periodicbackup',
            name='periodic_task',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.periodictask'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='periodicbackup',
            table='tb_periodic_backup',
        ),
    ]
