start-application-job:
  stage: start-application
  image: python:3.11
  before_script:
    - pip install -r requirements.txt
  script:
    - docker-compose build
    - docker-compose down
    - docker-compose up -d